
version: '3'
services:
  flask:
    build: flask/
    command: gunicorn -w 1 -b 0.0.0.0:5000 hello:app --reload
    environment:
      - FLASK_APP=hello.py 
      - PYTHONUNBUFFERED=True
    ports: 
      - "5000:5000"
    volumes: 
      - "./flask/:/home/flask"

   